spring:
  redis:
    host : localhost
    port : 6379
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql : true
logging:
  level:
    org:
      hibernate:
        sql : debug
        type : trace